services:
  sensor-service:
    image: svenschmidt1502/rpi4-motion
    container_name: hc-sr501
    restart: always
    privileged: true  # Benötigt für GPIO-Zugriff auf Raspberry Pi
    environment:
      - BROKER_IP=${BROKER_IP}
      - BROKER_PORT=${BROKER_PORT}
      - TOPIC_MOTION=${TOPIC_MOTION}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
    devices:
      - "/dev/:/dev/"  # Zugriff auf GPIO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
